# Generated by Django 5.1.3 on 2024-11-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Midia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporada',
            old_name='numero',
            new_name='numero_temporada',
        ),
        migrations.AlterUniqueTogether(
            name='temporada',
            unique_together={('serie', 'numero_temporada')},
        ),
    ]
