# Generated by Django 5.1.3 on 2025-01-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Midia', '0002_rename_serie_episodio_serie_temporada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='genero',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
