# Generated by Django 5.1.3 on 2024-12-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Midia', '0003_rename_midia_episodio_episodio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('USUARIO', 'Usuário')], max_length=40),
        ),
    ]
