# Generated by Django 5.1.3 on 2025-01-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Midia', '0003_alter_midia_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='duracao',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='midia',
            name='data_lancamento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='midia',
            name='nota',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='midia',
            name='titulo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
