# Generated by Django 5.1.3 on 2025-01-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Midia', '0004_alter_episodio_duracao_alter_midia_data_lancamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='poster',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
