# Generated by Django 5.1.3 on 2025-01-13 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Midia', '0005_midia_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigo',
            name='usuario1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amigo_usuario1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='amigo',
            name='usuario2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amigo_usuario2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
